<li id="layer_{{optionInfo.id}}" class="list-group-item layer-item">
    <div class="row">
        <div class="col-md-6" ng-hide="!optionInfo.options">
            <span>{{optionInfo.title}}</span>  
        </div>
        <div class="col-md-4">
            <div class="thumbnail-image" ng-show="optionInfo.thumbnail_image">
                <a ng-click="addLayerToDesign(optionInfo)" class="choose-thumbnail" ng-class="{'active' : isSelected}">
                    <img ng-if="optionInfo.thumbnail_image" ng-src="{{mediaUrl + optionInfo.thumbnail_image}}" />
                </a>
            </div>
        </div>
        <div class="col-md-2">
            <div class="action-btn pull-right">
                <a class="btn btn-xs btn-default expand-layer" ng-click="expandLayer(optionInfo)" ng-show="optionInfo.options">
                    <span class="glyphicon" ng-class="{'glyphicon-plus': expand === true, 'glyphicon-minus': expand === false}" aria-hidden="true"></span>
                </a>
            </div>
        </div>
    </div>
</li>