<div clas="pbp-media-wrapper">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">Product Builder Pro - Media</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <input type="file" accept="image/*"/>
                    <input type="text" value="" class="img-src form-control"/>
                </div>
                <div class="col-md-6">
                    
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-md-3">
                    <div class="thumbnail">
                        <img src="http://localhost/github/pbp/media/pbp/images/main/original_xbox.png" class="img-rounded">
                    </div>
                </div>
                <div class="col-sm-6 col-md-3">
                    <div class="thumbnail">
                        <img src="http://localhost/github/pbp/media/pbp/images/main/original_ps3.png" class="img-rounded">
                    </div>
                </div>
                <div class="col-sm-6 col-md-3">
                    <div class="thumbnail">
                        <img src="http://localhost/github/pbp/media/pbp/images/main/xbox.png" class="img-rounded">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
