<li id="layer_{{optionInfo.id}}" class="list-group-item">
    <div class="row">
        <div class="col-md-8">
            <span>{{optionInfo.title}}</span>  
        </div>
        <div class="col-md-4">
            <div class="action-btn pull-right" ng-show="optionInfo.parent_id == 0 && optionInfo.options">
                <a class="btn btn-xs btn-default expand-layer" ng-click="expandLayer(optionInfo)">
                    <span class="glyphicon" ng-class="{'glyphicon-plus': expand === true, 'glyphicon-minus': expand === false}" aria-hidden="true"></span>
                </a>
                <a class="btn btn-xs btn-info edit-layer" ng-click="editLayer(optionInfo);">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
                <a class="btn btn-xs btn-danger remove-layer" ng-click="removeLayer(optionInfo)">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                </a>
            </div>
            <div class="select-layer pull-right" ng-show="!optionInfo.options">
                <a class="btn btn-xs btn-success">
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Use
                </a>
            </div>
        </div>
    </div>
</li>