<?php $currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); ?>
<div class="selected-layer" ng-show="showLayer(layerStack[groupId])">
    <div class="panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $this->__("Selected Layers") ?></h3>
        </div>
        <div class="panel-body">
            <!--<pre>{{layerStack[groupId] | json}}</pre>-->
            <ul>
                <li ng-repeat="layer in layerStack[groupId]">
                    <div class="row">
                        <div class="col-xs-3">
                            <img ng-if="layer.main_image" class="thumbnail" ng-src="{{mediaUrl + layer.main_image}}" width="50px" />
                        </div>
                        <div class="col-xs-3">
                             {{layer.title}}
                        </div>
                        <div class="col-xs-3">
                             <strong><?php echo $currencySymbol ?>{{layer.price}}</strong>
                        </div>
                        <div class="col-xs-3">
                             <a ng-click="removeSelectedLayer(layer)"><span aria-hidden="true" class="glyphicon glyphicon-remove-sign"></span></a>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="row total-price">
                        <div class="col-xs-6">
                            <?php echo $this->__("Total") ?>
                        </div>
                        <div class="col-xs-3">
                            <?php echo $currencySymbol ?>{{getTotalPrice(layerStack[groupId])}}
                        </div>
                        <div class="col-xs-3">
                             
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
