<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <h2>
                <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                Product Builder Pro - Add Layer
            </h2>
        </div>
        <div class="col-lg-8">
            <div class="pull-right">
                <a class="btn btn-primary" ng-click="backOrCancel()">
                    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
                    <span>Back</span>
                </a>
                <a class="btn btn-success" ng-click="saveLayer()">
                    <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span>
                    <span>Save Layer</span>
                </a>
                <pbp-loading ng-if="isSaving"></pbp-loading>
                <a class="btn btn-warning" ng-click="backOrCancel()">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    <span>Cancel</span>
                </a>
            </div>
        </div>
    </div>
    <div class="row main-content">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title"><?php echo $this->__("Add New Layer Form") ?></h3>
                        </div>
                        <div class="panel-body">
                            <!--<pre>Data {{layerData | json}}</pre>-->
                            <!--
                            <div class="alert alert-warning" ng-show="!validForm()">
                                <?php echo $this->__("Please fill all required fields!") ?>
                            </div>-->
                            <form id="add_new_group_form" name="add_new_group_form" class="form-horizontal">
                                <div class="form-group" ng-class="{'has-error': !layerData.title}">
                                    <label for="layer_title" class="col-sm-2"><?php echo $this->__("Title") ?> <span class="required">*</span></label>
                                    <div class="col-sm-10">
                                        <input type="text" required ng-model="layerData.title" class="form-control" id="layer_title" name="title"/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="parent_id" class="col-sm-2"><?php echo $this->__("Parent") ?> <span class="required">*</span> </label>
                                    <div class="col-sm-10">
                                        <select class="form-control" ng-model="layerData.parent_id" id="parent_id" name="parent_id" ng-options="parent.id as parent.title disable when parent.id == id && id != 0 for parent in parents">
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="layer_price" class="col-sm-2"><?php echo $this->__("Price") ?></label>
                                    <div class="col-sm-10">
                                        <input type="text" ng-model="layerData.price" class="form-control" id="layer_price" name="price"/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="thumbnail_image" class="col-sm-2"><?php echo $this->__("Thumbnail Image") ?></label>
                                    <div class="col-sm-10">
                                        <pbp-media img-src="{{layerData.thumbnail_image}}" name="thumbnail_image"></pbp-media>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="default_image" class="col-sm-2"><?php echo $this->__("Main Image") ?></label>
                                    <div class="col-sm-10">
                                        <pbp-media img-src="{{layerData.main_image}}" name="main_image"></pbp-media>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="product_description" class="col-sm-2"><?php echo $this->__("Description") ?></label>
                                    <div class="col-sm-10">
                                        <textarea id="product_description" ng-model="layerData.description" class="form-control"></textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="layer_position" class="col-sm-2"><?php echo $this->__("Position") ?></label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" ng-model="layerData.position" id="layer_position" name="position"/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="layer_status" class="col-sm-2"><?php echo $this->__("Status") ?></label>
                                    <div class="col-sm-10">
                                        <select name="layer_status" id="layer_status" ng-model="layerData.status" class="form-control">
                                            <option ng-selected="layerData.status == 1" value="1"><?php echo $this->__("Enable") ?></option>
                                            <option ng-selected="layerData.status == 2" value="2"><?php echo $this->__("Disable") ?></option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="is_required" class="col-sm-2"><?php echo $this->__("Is Required") ?></label>
                                    <div class="col-sm-10">
                                        <select name="is_required" ng-model="layerData.is_required" id="is_required" class="form-control">
                                            <option value="1"><?php echo $this->__("Yes") ?></option>
                                            <option value="2"><?php echo $this->__("No") ?></option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="select_type" class="col-sm-2"><?php echo $this->__("Select Type") ?></label>
                                    <div class="col-sm-10">
                                        <select id="select_type" name="select_type" ng-model="layerData.select_type" class="form-control">
                                            <option value="1"><?php echo $this->__("Single") ?></option>
                                            <option value="2"><?php echo $this->__("Multiple") ?></option>
                                        </select>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>