<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <h2>
                <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                Product Builder Pro - Add Layer
            </h2>
        </div>
        <div class="col-lg-8">
            <h3 class="pull-right">
                <a class="btn btn-primary" href="#/">
                    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
                    <span>Back</span>
                </a>
                <a class="btn btn-success" href="#/save-layer">
                    <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span>
                    <span>Save Layer</span>
                </a>
                <a class="btn btn-warning">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    <span>Cancel</span>
                </a>
            </h3>
        </div>
    </div>
    <div class="row main-content">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title"><?php echo $this->__("Add New Layer Form") ?></h3>
                        </div>
                        <div class="panel-body">
                            <form id="add_new_group_form" class="form-horizontal">
                                <div class="form-group">
                                    <label for="layer_title" class="col-sm-2"><?php echo $this->__("Title") ?></label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="layer_title" name="title"/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="parent_id" class="col-sm-2"><?php echo $this->__("Parent") ?></label>
                                    <div class="col-sm-10">
                                        <select class="form-control" id="parent_id" name="parent_id">
                                            <option>Button</option>
                                            <option>Track Pad</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="group_id" class="col-sm-2"><?php echo $this->__("Group") ?></label>
                                    <div class="col-sm-10">
                                        <select class="form-control" id="group_id" name="group_id">
                                            <option>Ps3</option>
                                            <option>Shoe</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="layer_price" class="col-sm-2"><?php echo $this->__("Price") ?></label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="layer_price" name="price"/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="thumbnail_image" class="col-sm-2"><?php echo $this->__("Thumbnail Image") ?></label>
                                    <div class="col-sm-10">
                                        <pbp-media></pbp-media>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="default_image" class="col-sm-2"><?php echo $this->__("Main Image") ?></label>
                                    <div class="col-sm-10">
                                        <input type="file" id="main_image" name="main_image" accept="image/*"/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="product_description" class="col-sm-2"><?php echo $this->__("Description") ?></label>
                                    <div class="col-sm-10">
                                        <textarea id="product_description" class="form-control"></textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="layer_position" class="col-sm-2"><?php echo $this->__("Position") ?></label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="layer_position" name="position"/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="layer_status" class="col-sm-2"><?php echo $this->__("Status") ?></label>
                                    <div class="col-sm-10">
                                        <select name="layer_status" id="layer_status" class="form-control">
                                            <option value="1"><?php echo $this->__("Enable") ?></option>
                                            <option value="2"><?php echo $this->__("Disable") ?></option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="is_required" class="col-sm-2"><?php echo $this->__("Is Required") ?></label>
                                    <div class="col-sm-10">
                                        <select name="is_required" id="is_required" class="form-control">
                                            <option value="1"><?php echo $this->__("Yes") ?></option>
                                            <option value="2"><?php echo $this->__("No") ?></option>
                                        </select>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>