<div class="container" ng-controller="pbpController">
    <div class="row">
        <div class="col-lg-4">
            <h2>
                <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                <?php echo $this->__("Edit Option") ?>
            </h2>
        </div>
        <div class="col-lg-8">
            <h3 class="pull-right">
                <a class="btn btn-primary" href="#/">
                    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
                    <span>Back</span>
                </a>
                <a class="btn btn-success" href="#/save_layer">
                    <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span>
                    <span>Save Option</span>
                </a>
                <a class="btn btn-warning">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    <span>Cancel</span>
                </a>
            </h3>
        </div>
    </div>
    <div class="row main-content">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h1>ID: {{currentOption.id || 0}}</h1>
                    <div class="form-group">
                        <label>Layer Title</label>
                        <input type="text" class="form-control" ng-model="currentOption.title"/>
                    </div>
                    <div class="form-group">
                        <label>Thumbnail</label>
                        <input type="text" class="form-control" ng-model="currentOption.thumbnail"/>
                        <img src="{{currentOption.thumbnail}}" />
                    </div>
                    <div class="form-group">
                        <label>Main Image</label>
                        <input type="text" class="form-control" ng-model="currentOption.main_image"/>
                        <img src="{{currentOption.main_image}}" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>