<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <h2>
                <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                Product Builder Pro
            </h2>
        </div>
        <div class="col-lg-8">
            <h3 class="pull-right">
                <a ng-show="!isDesignSample" class="btn btn-md btn-success" href="#/add-group/0">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    <span><?php echo $this->__("Add Customize Product") ?></span>
                </a>
                <a ng-show="isDesignSample" class="btn btn-success" ng-click="saveSampleDesign()">
                    <span aria-hidden="true" class="glyphicon glyphicon-floppy-disk"></span>
                    <span><?php echo $this->__("Save This Design") ?></span>
                </a>
                <a ng-show="isDesignSample" class="btn btn-warning" ng-click="cancelSampleDesign()">
                    <span aria-hidden="true" class="glyphicon glyphicon-remove"></span>
                    <span><?php echo $this->__("Cancel") ?></span>
                </a>
            </h3>
        </div>
    </div>
    <div class="row main-content">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="alert alert-info" ng-if="!groups" style="text-align: center;">
                        <?php echo $this->__("There is no customize product!") ?>
                    </div>
                    <div ng-show="!isDesignSample" class="pbp-group-item" ng-repeat="group in groups">
                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <h3 class="panel-title">
                                    <a class="btn btn-sm">{{group.title}}</a>
                                    <div class="pull-right">
                                        <a class="btn btn-info btn-sm" href="#add-group/{{group.id}}">
                                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                        </a>
                                        <a class="btn btn-danger btn-sm" ng-click="removeGroup(group)">
                                            <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
                                        </a>
                                    </div>
                                </h3>
                            </div>
                            <div class="panel-body">
                                <!--<pre>{{group | json}}</pre>-->
                                <div class="row">
                                    <div class="col-md-6">
                                        <a class="btn btn-sm btn-primary" ng-click="addLayerForGroup(group)">
                                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                                            <span><?php echo $this->__("Add New Layer") ?></span>
                                        </a>
                                    </div>
                                    <div class="col-md-6">
                                        <a class="btn btn-sm btn-primary" ng-click="designSample(group)">
                                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                            <span><?php echo $this->__("Design Sample") ?></span>
                                        </a>
                                    </div>
                                </div>
                                <br/>
                                <div class="row">
                                    <div class="col-md-6">
                                        <pbp-option-collection level="0" option-list="group.layers"></pbp-option-collection>    
                                    </div>
                                    <div class="col-md-6">
                                        <div class="sample-design">
                                            <span ng-if="!group.sample[0].layers" style="text-align: center; width: 100%;">There is no sample design</span>
                                            <div class="product-design-area" id="pbp_{{group.id}}" style="position: relative; width: 100%;">
                                                <img src="{{mediaUrl + layer.main_image}}" style="width: 100%; position: absolute;" ng-repeat="layer in group.sample[0].layers"/>
                                            </div>
                                        </div>
                                    </div>
                                    <!--
                                    <div class="col-md-3">
                                        <div class="product-design-area" id="pbp_{{group.id}}" style="position: relative; width: 100%;">
                                            <img src="{{mediaUrl + layer.main_image}}" style="width: 100%; position: absolute;" ng-repeat="layer in layerStack[group.id]"/>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <selected-layer group-id="{{group.id}}" layer-stack="layerStack"></selected-layer>
                                    </div>-->
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--Design Sample Iframe-->
                    <div class="row" ng-show="isDesignSample">
                        <div class="col-md-12">
                            <h4 class="alert alert-info" style="text-align: center; font-weight: bold;">{{designSampleTitle}}</h4>
                            <iframe src="{{designSampleURL}}" width="100%;" height="500px"></iframe>    
                        </div>
                    </div>
                    <!-- End design sample -->
                </div>
            </div>
        </div>
    </div>
</div>