<?php $jsPbp = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>
<?php $currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); ?>
<link href="<?php echo $jsPbp ; ?>pbp/css/product-builder.css" rel="stylesheet"/>
<link href="<?php echo $jsPbp ; ?>pbp/css/accordion.css" rel="stylesheet"/>
<link href="<?php echo $jsPbp ; ?>pbp/css/tooltip.css" rel="stylesheet"/>
<link href="<?php echo $jsPbp ; ?>pbp/css/styles.css" rel="stylesheet"/>
<link href='http://fonts.googleapis.com/css?family=Roboto:500,300,700,400&subset=cyrillic,cyrillic-ext,latin,latin-ext,vietnamese' rel='stylesheet' type='text/css'>
<!-- pbpApp -->
<input type="hidden" value="<?php echo Mage::helper("productbuilderpro")->getBaseUrl(); ?>" id="mst_base_url" />
<input type="hidden" value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>" id="mst_media_url" />
<input type="hidden" value="<?php echo $this->getData("group_id") ?>" id="current_group_id" />
<div style="display: none;" class="product-builder-wrap" ng-app="pbpApp" ng-controller="pbpFrontendController">
    <div class="pd-left">
        <!-- Product Builder Tools -->
        <div class="pd-tools accordion">
             <div ng-cloak class="accordion-section as{{layer.id}}" ng-repeat="layer in group.layers track by layer.id">
                <a id="accordion-arrow-{{layer.id}}" class="accordion-section-title tooltip right" ng-click="expand(layer)" ng-class="{'active' : $index == 0}">
                    <span style="background: transparent url('{{mediaUrl + layer.thumbnail_image}}') no-repeat scroll left center;">
                        {{layer.title}}
                    </span>
                    <div class="tooltip-content" ng-if="layer.description">{{layer.description}}</div>
                </a>
                <div id="accordion-{{layer.id}}" class="accordion-section-content" ng-class="{'open' : $index == 0}">
                    <ul class="colours" ng-if="layer.selected_level == 1 && layer.options">
                        <li ng-class="{'selected' : layerStack[currentGroupId][level1Layer.id]}" ng-repeat="level1Layer in layer.options">
                            <a ng-click="addLayerToDesign(level1Layer, layer)" class="layer-item">
                                <span style="display: none;" class="layer-title">{{level1Layer.title}}</span>
                                <img ng-if="level1Layer.thumbnail_image" ng-src="{{mediaUrl + level1Layer.thumbnail_image}}" title="{{level1Layer.title}}" alt="{{level1Layer.title}}" />
                            </a>
                        </li>
                    </ul>
                    <div ng-if="layer.selected_level == 2 && layer.options" class="level1" ng-repeat="level1Layer in layer.options">
                        <span ng-if="level1Layer.options" class="label">{{level1Layer.title}}</span>
                        <ul class="colours" ng-if="level1Layer.options">
                            <li ng-class="{'selected' : layerStack[currentGroupId][level2Layer.id]}" ng-repeat="level2Layer in level1Layer.options">
                                <a ng-click="addLayerToDesign(level2Layer, layer)" class="select-layer">
                                    <span style="display: none;" class="layer-title">{{level2Layer.title}}</span>
                                    <img ng-if="level2Layer.thumbnail_image" ng-src="{{mediaUrl + level2Layer.thumbnail_image}}"  title="{{level2Layer.title}}" alt="{{level2Layer.title}}" />
                                </a>
                            </li>
                        </ul>
                    </div>
                </div><!--end .accordion-section-content-->
            </div><!--end .accordion-section-->
        </div><!--end .accordion-->
        <!-- End Product Builder Tools -->
        <!-- Product Builder Buttons -->
        <ul class="pd-buttons">
            <li class="shu-btn">
                <a ng-click="shuffleDesign()"><span>Shuffle</span></a>
            </li>
            <li class="last re-btn">
                <a href="#"><span>Reset</span></a>
            </li>
        </ul><!-- Product Builder Buttons -->

    </div>
    <div class="pd-right">
        <div class="pd-main">
            <div class="pd-layer" style="position: relative;">
                <img class="layer_image" 
                     ng-if="layer.main_image" 
                     style="z-index: {{layer.root_zindex}}; position: absolute; width: 100%;"
                     ng-repeat="layer in layerStack[currentGroupId]"
                     ng-src="{{mediaUrl + layer.main_image}}" />
            </div>
            <div class="pd-share">
                <h3 class="label">Share</h3>
                <div class="share-list">
                    <span class='st_facebook_large' displayText='Facebook'></span>
                    <span class='st_twitter_large' displayText='Tweet'></span>
                    <span class='st_googleplus_large' displayText='Google +'></span>
                    <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
                    <script type="text/javascript">stLight.options({publisher: "ba26b9c8-1fff-46a0-94b3-39c58d5b3e3b", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
                </div>
            </div>
        </div>
        <div class="pd-bottom">
            <div class="pd-overview">
                <h3 class="title"><?php echo $this->__("Selected Items") ?>:</h3>
                <dl>
                    <div ng-repeat="selectedLayer in layerStack[currentGroupId]">
                        <dt><span>{{selectedLayer.root_title}}:</span></dt>
                        <dd>{{selectedLayer.title}}</dd>
                    </div>
                </dl>
            </div>
            <div class="pd-summary">
                <h3 class="title"><span><?php echo $this->__("Sub Total") ?>:<span class="total-price"><?php echo $currencySymbol ?>{{getTotalPrice()}}</span></h3>
                <a ng-click="addToCart()" class="btn btn-cart">
                    <span><?php echo $this->__("Add To Cart") ?></span>
                </a>
                <pbp-loading ng-if="isSaving"></pbp-loading>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo $jsPbp; ?>pbp/js/angular/angular.js"></script>
<script src="<?php echo $jsPbp; ?>pbp/js/angular/angular-route.min.js"></script>
<script src="<?php echo $jsPbp; ?>pbp/js/angular/angular-animate.js"></script>
<script src="<?php echo $jsPbp; ?>pbp/js/core/app.js"></script>
<script src="<?php echo $jsPbp; ?>pbp/js/core/routes.js"></script>
<script src="<?php echo $jsPbp; ?>pbp/js/core/services.js"></script>
<script src="<?php echo $jsPbp; ?>pbp/js/frontend/frontend_controllers.js"></script>
<script src="<?php echo $jsPbp; ?>pbp/js/frontend/frontend_directives.js"></script>